server:
  servlet:
    context-path: /api/v1/poli
  port: 9080
spring:
  datasource:
    url: jdbc:h2:mem:task
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
  application:
    name: todo-app2